version: "3.7"

services:
  web:
    build:
      context: .
      target: python-base
    image: trello-clone-api
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
    ports:
      - 8000:8000
